#ifndef MULTI_MASTER_MACRO_HEADER
#define MULTI_MASTER_MACRO_HEADER

/*macro for wei*/
#define MULTI_MASTER_WEI_NORMAL
#define MULTI_MASTER_WEI_COFIG_DEBUG
//#define MULTI_MASTER_WEI_COFIG_GROUP_DEBUG
//#define MULTI_MASTER_WEI_BUFFER_DEBUG
#define MULTI_MASTER_WEI_SYSVAR

#endif // !MULTI_MASTER_MACRO_HEADER
